name: CI Jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar Jest
      run: npm test

    - name: Mensaje final
      run: echo "🚀 Deploy exitoso"
